import https from 'https';
import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';

const NIEM_XSD_URL =
  'https://raw.githubusercontent.com/niemopen/niem-model/6.0-ps02/xsd/codes/ncic.xsd';

const VEHICLE_CODE_TYPES = ['VMA', 'VMO', 'VCO', 'VST'] as const;
type VehicleCodeType = (typeof VEHICLE_CODE_TYPES)[number];

interface CodeEntry {
  code: string;
  rawName: string;
}

interface MapPair {
  forward: Record<string, string>;
  reverse: Record<string, string>;
}

function fetchUrl(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode} fetching ${url}`));
          return;
        }
        const chunks: Buffer[] = [];
        res.on('data', (chunk: Buffer) => chunks.push(chunk));
        res.on('end', () => resolve(Buffer.concat(chunks).toString('utf-8')));
        res.on('error', reject);
      })
      .on('error', reject);
  });
}

function extractEntries(xsd: string, typePrefix: string): CodeEntry[] {
  const typeRegex = new RegExp(
    `name="${typePrefix}CodeSimpleType"[\\s\\S]*?</xs:simpleType>`
  );
  const block = xsd.match(typeRegex)?.[0];
  if (!block) {
    console.warn(`  WARNING: ${typePrefix}CodeSimpleType not found in XSD`);
    return [];
  }

  const entryRegex =
    /<xs:enumeration value="([^"]+)"[\s\S]*?<xs:documentation>([^<]+)<\/xs:documentation>/g;
  const entries: CodeEntry[] = [];
  let match: RegExpExecArray | null;
  while ((match = entryRegex.exec(block)) !== null) {
    entries.push({
      code: match[1].trim(),
      rawName: match[2].trim(),
    });
  }
  return entries;
}

/**
 * Normalizes a raw NIEM name for use as a reverse-lookup key.
 *
 * Raw names often contain city/state info ("HONDA%TOKYO JAPAN"),
 * parenthetical notes ("FORD (ALSO SEE ENGLISH FORD)"), and
 * corporate suffixes ("HONDA MOTOR CO., LTD") that would prevent
 * a simple name → code lookup. This strips all of that so
 * getCode('Honda') resolves to 'HOND'.
 */
function normalizeNameForReverse(rawName: string): string {
  let name = rawName.split('%')[0].trim();
  name = name.replace(/\s*\([^)]*\)/g, '').trim();

  const suffixes = [
    'MOTOR CO., LTD',
    'MOTOR CO.',
    'MOTORS, INC.',
    'MOTORS INC.',
    'MOTORS',
    'MFG. CO.',
    'MFG CO.',
    'CO., LTD',
    'CO.,LTD',
    'INC.',
    'CORP.',
    'CO.',
    'LTD.',
    'LTD',
  ];
  const upper = name.toUpperCase();
  for (const suffix of suffixes) {
    if (upper.endsWith(' ' + suffix)) {
      name = name.slice(0, -(suffix.length + 1)).trim();
      break;
    }
  }

  return name.toUpperCase();
}

function buildMapPair(entries: CodeEntry[]): MapPair {
  const forward: Record<string, string> = {};
  const reverse: Record<string, string> = {};

  for (const { code, rawName } of entries) {
    const displayName = rawName.split('%')[0].trim();
    forward[code] = displayName;

    const key = normalizeNameForReverse(rawName);
    if (key && !reverse[key]) {
      reverse[key] = code;
    }
  }

  return { forward, reverse };
}

async function main(): Promise<void> {
  console.log('Fetching NIEM 6.0 ncic.xsd from GitHub...');
  const xsd = await fetchUrl(NIEM_XSD_URL);
  console.log(`  Fetched ${(xsd.length / 1024).toFixed(0)} KB`);

  const data: Partial<Record<VehicleCodeType, MapPair>> = {};

  for (const typeKey of VEHICLE_CODE_TYPES) {
    const entries = extractEntries(xsd, typeKey);
    console.log(`  ${typeKey}: ${entries.length} entries`);
    data[typeKey] = buildMapPair(entries);
  }

  const output =
    `// AUTO-GENERATED by scripts/build-data.ts — DO NOT EDIT MANUALLY\n` +
    `// Source: NIEM 6.0 PS02 (niemopen/niem-model@6.0-ps02)\n` +
    `// Generated: ${new Date().toISOString()}\n` +
    `// VMA: ${Object.keys(data.VMA!.forward).length} vehicle makes\n` +
    `// VMO: ${Object.keys(data.VMO!.forward).length} vehicle models\n` +
    `// VCO: ${Object.keys(data.VCO!.forward).length} vehicle colors\n` +
    `// VST: ${Object.keys(data.VST!.forward).length} vehicle styles\n\n` +
    `import type { NcicVehicleData } from '../types.js';\n\n` +
    `export const NCIC_VEHICLE_DATA: NcicVehicleData = ${JSON.stringify(data, null, 2)};\n`;

  const outDir = join(process.cwd(), 'src/data');
  mkdirSync(outDir, { recursive: true });
  const outPath = join(outDir, 'ncic-vehicle.ts');
  writeFileSync(outPath, output, 'utf-8');
  console.log(`\nWritten to ${outPath}`);
}

main().catch((err: unknown) => {
  console.error('Build failed:', err);
  process.exit(1);
});
